title: Pattern Kit

paths:
  data:
    - src/data
  schemas:
    - src/schemas
  templates:
    - src/templates
  docs:
    - src/docs
  sg:
    - src/styleguide
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .sg.md
categories:
    - Pattern
    - Component
    - Layout
assets:
  css:
    - /src/css/style.css
  js:
  footer_js:


